steps:
- id: install_packages
  name: node:12-alpine
  args: ['npm', 'install']
- id: prerender_browser_files
  name: node:12-alpine
  args: ['npm', 'run', 'prerender']
  waitFor:
  - install_packages
- id: copy_prerendered_files
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp','-r','dist/test-cloud-build/browser/*', 'gs://${_ANGULAR_APP_BUCKET_PATH}']
  waitFor:
  - prerender_browser_files